spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//database-1.c7a64tptshs7.ap-south-1.rds.amazonaws.com:1521/orcl
    username: tiger
    password: tiger_2022
server:
  port: 8080